on: workflow_dispatch

name: Common Base for All Github Actions

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.2'
