on: workflow_dispatch

name: Common Base for All Github Actions

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Ensure AWS CLI exists and credentials works.
        run: aws s3 ls

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.2'

      - name: Install yarn
        run: npm i -g yarn

      - name: Setup .env files
        run: |
          echoerr "Creating api/function-api/.env"
          DOTENV=api/function-api/.env
          echo DEPLOYMENT_KEY=stage > ${DOTENV}.template
          echo AWS_REGION=us-west-2 >> ${DOTENV}.template
          echo API_SERVER=https://stage.us-west-2.fusebit.io >> ${DOTENV}.template
          echo > ${DOTENV}.bootstrap
