export declare enum Permissions {
    allPermissions = "*",
    addAccount = "global:add:account",
    getAccount = "account:get",
    updateAccount = "account:update",
    deleteAccount = "global:delete:account",
    addSubscription = "global:add:subscription",
    getSubscription = "subscription:get",
    updateSubscription = "subscription:update",
    deleteSubscription = "global:delete:subscription",
    allIssuer = "issuer:*",
    addIssuer = "issuer:add",
    getIssuer = "issuer:get",
    updateIssuer = "issuer:update",
    deleteIssuer = "issuer:delete",
    allUser = "user:*",
    addUser = "user:add",
    getUser = "user:get",
    updateUser = "user:update",
    deleteUser = "user:delete",
    initUser = "user:init",
    allClient = "client:*",
    addClient = "client:add",
    getClient = "client:get",
    updateClient = "client:update",
    deleteClient = "client:delete",
    initClient = "client:init",
    getAudit = "audit:get",
    allStorage = "storage:*",
    getStorage = "storage:get",
    putStorage = "storage:put",
    deleteStorage = "storage:delete",
    allFunction = "function:*",
    putFunction = "function:put",
    getFunction = "function:get",
    logFunction = "function:post-logs",
    exeFunction = "function:execute",
    allRegistry = "registry:*",
    configRegistry = "registry-config:put",
    getRegistry = "registry:get",
    putRegistry = "registry:put",
    deleteRegistry = "registry:delete"
}
export declare const RestrictedPermissions: string[];
export declare const UserPermissions: string[];
export declare const isSpecialized: (permission: Permissions, query: string) => boolean;
//# sourceMappingURL=permissions.d.ts.map