declare module '*.png';
declare module '*.gif';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.webp';
declare module '*.ico';
declare module '*.svg';
declare module '*.xml';
declare module '*.webmanifest';
