// Generated by https://quicktype.io

export interface JestOutput {
  numFailedTestSuites: number;
  numFailedTests: number;
  numPassedTestSuites: number;
  numPassedTests: number;
  numPendingTestSuites: number;
  numPendingTests: number;
  numRuntimeErrorTestSuites: number;
  numTodoTests: number;
  numTotalTestSuites: number;
  numTotalTests: number;
  openHandles: any[];
  snapshot: Snapshot;
  startTime: number;
  success: boolean;
  testResults: TestResult[];
  wasInterrupted: boolean;
}

export interface Snapshot {
  added: number;
  didUpdate: boolean;
  failure: boolean;
  filesAdded: number;
  filesRemoved: number;
  filesRemovedList: any[];
  filesUnmatched: number;
  filesUpdated: number;
  matched: number;
  total: number;
  unchecked: number;
  uncheckedKeysByFile: any[];
  unmatched: number;
  updated: number;
}

export interface TestResult {
  assertionResults: AssertionResult[];
  endTime: number;
  message: string;
  name: string;
  startTime: number;
  status: Status;
  summary: string;
  coverage?: Coverage;
}

export interface AssertionResult {
  ancestorTitles: string[];
  failureMessages: string[];
  fullName: string;
  location: null;
  status: Status;
  title: string;
}

export enum Status {
  Failed = 'failed',
  Passed = 'passed',
  Pending = 'pending',
  Todo = 'todo',
}

export interface Coverage {}
