import { ArgType, Command } from '@5qtrs/cli';
import { EOL } from 'os';

export class InitCommand extends Command {
  public static async create() {
    return new InitCommand();
  }
  private constructor() {
    super({
      name: 'CLI Initialize',
      cmd: 'init',
      summary: 'Initialize the CLI',
      description: 'Initializes use of the CLI using a CLI init token generated by an account admin.',
      arguments: [
        {
          name: 'token',
          description: 'The user or client CLI init token generated by an account admin.',
        },
      ],
      modes: ['init'],
    });
  }
}
