export { Home, HomeProps } from './home';
export { Blog } from './blog';
export { About } from './About';
export { Legal } from './Legal';
export { Support } from './Support';
export { Privacy } from './Privacy';
export { Terms } from './Terms';
export { Route } from './Route';
export { Contact } from './Contact';
export { Careers } from './Careers';
