apiVersion: 1

datasources:
#- name: Prometheus
#  type: prometheus
#  access: proxy
#  orgId: 1
#  url: http://prometheus:9090
#  basicAuth: false
#  isDefault: false
#  version: 1
#  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'acc-123456'
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: (?:traceID|trace_id)=(\w+)
        name: TraceID
        url: $${__value.raw}
      - name: ExternalTraceId
        matcherRegex: (?:traceID|trace_id)=(\w+)
        url: http://localhost:3001/$${__value.raw}
        title: Monkeys
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'acc-123456'
