remote_theme: "pmarsceill/just-the-docs@v0.2.7"
repository: "fivequarters/q5"
title: "Fusebit Docs"
description: "The one-stop shop for all of our conceptual and API docs"
permalink: pretty
heading_anchors: true
exclude: ["README.md"]
footer_content: "&copy; 2019-2020 Fusebit - All Rights Reserved"
logo: "/assets/img/FusebitLogo.png"

# "Just the Docs" theme
search_enabled: true
aux_links:
  "Fusebit home":
    - "https://fusebit.io"
  "Fusebit Slack":
    - "https://fusebitio.slack.com"
