###################################################################
# Auto-created by the cicd-actions tool
on: pull_request
name: Delete Duplicate Function-API Test Runs
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.TOKEN_GITHUB }}
          workflow_id: 11826632
          all_but_latest: true
