###################################################################
# Auto-created by the cicd-actions tool
on: workflow_dispatch
name: Publish API Documentation to Readme.com
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: package-versions
        run: ./tool/cicd/actions/scripts/export_versions.sh
      - name: Discovered versions
        run: >
          echo "Versions: function_api/${{env.VERSION_FUNCTION_API}}
          fuse-cli/${{env.VERSION_FUSEBIT_CLI}}
          fuse-ops/${{env.VERSION_FUSEBIT_OPS_CLI}}"
      - name: Publish the OpenAPI docs for v1 to Readme.Com
        uses: readmeio/rdme@7.2.0
        with:
          rdme: >-
            openapi ./api/function-api/api_v1.yaml --key=${{
            secrets.README_COM_API_KEY }} --id=${{ secrets.README_COM_V1_ID }}
      - name: Publish the OpenAPI docs for v2 to Readme.Com
        uses: readmeio/rdme@7.2.0
        with:
          rdme: >-
            openapi ./api/function-api/api_v2.yaml --key=${{
            secrets.README_COM_API_KEY }} --id=${{ secrets.README_COM_V2_ID }}
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pr-review
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pr-review
          status: FAILED
          color: danger
