###################################################################
# Auto-created by the cicd-actions tool
name: Publish API Documentation to Readme.com

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish the OpenAPI docs for v2 to Readme.Com
        uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{secrets.README_COM_OAS_KEY}}
          oas-file-path: "./api/function-api/api_v2.yaml"
          api-version: "v1.0"
