on: pull_request
name: Test CLI on NPM 7
jobs:
  deploy:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Install yarn
        run: npm i -g yarn
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.13
      - name: Install and test CLI
        run: >
          echo 'Installing fuse'

          node -v

          npm -v
