###################################################################
# Auto-created by the cicd-actions tool
on: workflow_dispatch
name: Test version checks
jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy
    steps:
      - name: Upgrade aws-cli
        run: >
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o
          "awscliv2.zip"

          unzip awscliv2.zip >/dev/null

          sudo ./aws/install --update

          /usr/local/bin/aws --version

          aws --version
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: package-versions
        run: ./tool/cicd/actions/scripts/export_versions.sh
      - name: Discovered versions
        run: >
          echo "Versions: function_api/${{env.VERSION_FUNCTION_API}}
          fuse-cli/${{env.VERSION_FUSEBIT_CLI}}
          fuse-ops/${{env.VERSION_FUSEBIT_OPS_CLI}}"
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pr-review
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pr-review
          status: FAILED
          color: danger
