###################################################################
# Auto-created by the cicd-actions tool
on: workflow_dispatch
name: Test Function-API (Manual)
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Cleanup Orphaned Resources
        run: ./tool/cicd/actions/scripts/clean_env.sh
      - name: Test - function-api
        env:
          FUSE_PROFILE: cicd
        run: ./tool/cicd/actions/scripts/test_function_api.sh
