on: pull_request
name: Test NPM Install
jobs:
  test-npm-install:
    name: NPM Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.22.6, 14.17.2, 15.13.0, 16.11.0]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and test CLI
        run: >
          echo 'Installing fuse'

          node -v

          npm -v

          npm i -g @fusebit/cli

          fuse
