on:
  schedule:
    - cron: "30 3 * * *"
name: Test CLI on NPM 7
jobs:
  deploy:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.13
      - name: Install and test CLI
        run: >
          echo 'Installing fuse'

          node -v

          npm -v

          npm install -g @fusebit/cli

          fuse
